---
kind: pipeline
type: exec
name: default
platform:
  os: linux
  arch: arm64
steps:
- name: build
  commands:
  - libtoolize
  - aclocal
  - autoconf
  - automake --add-missing
  - ./configure --prefix=/opt/cloud/cuser
  - make
  - make install
trigger:
  branch:
  - master
