language: c
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libssl-dev libsqlite3-dev autotools-dev autoconf libtool libtool-bin
script:
  - autoconf
  - automake --add-missing
  - ./configure
  - make
